#!/usr/bin/env bash
mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua


# link wholesales
# for f in `find . -regex ".*\.vim$"`; do
# for f in `find .*\.vim$" | sed 's|^./||'`; do
for f in `find . -regex ".*\.vim$" | sed -e 's,^\./,,'`; do
  rm -rf ~/.config/nvim/$f
  ln -s ~/code/dotfiles/$f ~/.config/nvim/$f
done
